project:
  type: website

website:
  title: "Zachary Wood"
  site-url: https://wood-zachary.github.io
  description: >-
    Portfolio of Zachary Wood, a computer science student at Harvey Mudd College focused on FPGA design, computer architecture, and embedded systems.
  favicon: images/headshot.jpg
  navbar:
    left:
    - href: index.qmd
      text: Home
    - href: experience.qmd
      text: Experience
    - href: projects.qmd
      text: Class Projects
    - href: labs.qmd
      text: Microprocessor Labs
    - href: blog.qmd
      text: Blog
    - href: resources.qmd
      text: Resources
    right:
    - icon: github
      href: https://github.com/wood-zachary
      target: _blank
    - icon: linkedin
      href: https://www.linkedin.com/in/zwoodhmc/
      target: _blank

format:
  html:
    theme:
      light:
      - cosmo
      - brand
      dark: darkly
    css: styles.css
    toc: true
