---
title: "Initial Reflections"
description: "Some of my goals for my semester in MicroPs"
author: "Zachary Wood"
date: "9/2/26"
categories:
  - reflection
  - labreport
draft: false
---

I am a computer science major who wants to pursue computer engineering in grad school and in my career, and I am broadly interested in three categories of CE/EE: SoC development, ASIC development, and FPGA development. A lot of what I have applied to during this summer for Summer 2027 have been FPGA engineer internships at high-frequency trading companies since they have a quick development loop that's constantly introducing problems, but now that Nvidia and AMD have posted their internship a week or so ago, I am also applying to those since i am very interested in the kind of broad subject of computer architecture. I have experience programming microcontrollers and some experience working with FPGAs, but I don't much lab/project experience for something like a portfolio for either of the two, and I have not worked on something that incorporated both, so I am very excited to do that this semester. Overall, my main goals for this summer are to get more experience in using C/C++ for microcontroller programming, using SystemVerilog for FPGAs, developing projects from specs, parsing larger and denser datasheets, and I want to build a portfolio of my work and progress.